mongodb:
    image: erangaeb/senzmongodb:0.1
    container_name: senzmongodb
    volumes:
        ['$MONGO_DATA_DIR:/data/db']
    ports:
        - 27017:27017


switch:
    image: erangaeb/senzswitch:0.57
    container_name: senzswitch
    ports:
        - 7070:7070
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - SWITCH_MODE=${SWITCH_MODE}
    volumes:
        ['$SWITCH_LOGS_DIR:/app/logs', '$SWITCH_KEYS_DIR:/app/.keys']
    links:
        - mongodb


stream:
    image: erangaeb/streamswitch:0.14
    container_name: streamswitch
    ports:
        - 9090:9090/udp
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - SWITCH_MODE=${SWITCH_MODE}
    volumes:
        ['$STREAM_LOGS_DIR:/app/logs', '$STREAM_KEYS_DIR:/app/.keys']
    links:
        - mongodb


rahasakweb:
    image: hpcal1/rahasakweb:0.2
    container_name: rahasakweb
    ports:
        - 80:8080


rahasakdashboard:
    image: hpcal1/senziesdashboard:0.3
    container_name: rahasakdashboard
    ports:
        - 4000:4000
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - MONGO_DB=${MONGO_DB}
    links:
        - mongodb
