mongodb:
    image: erangaeb/senzmongodb:0.1
    container_name: senzmongodb
    volumes:
        ['$MONGO_DATA_DIR:/data/db']
    ports:
        - 27017:27017


switch:
    image: erangaeb/senzswitch:0.57
    container_name: senzswitch
    ports:
        - 7070:7070
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - SWITCH_MODE=${SWITCH_MODE}
    volumes:
        ['$SWITCH_LOGS_DIR:/app/logs', '$SWITCH_KEYS_DIR:/app/.keys']
    links:
        - mongodb


stream:
    image: erangaeb/streamswitch:0.14
    container_name: streamswitch
    ports:
        - 9090:9090/udp
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - SWITCH_MODE=${SWITCH_MODE}
    volumes:
        ['$STREAM_LOGS_DIR:/app/logs', '$STREAM_KEYS_DIR:/app/.keys']
    links:
        - mongodb


rahasakweb:
    image: hpcal1/rahasakweb:0.2
    container_name: rahasakweb
    ports:
        - 8080:8080


rahasakdashboard:
    image: hpcal1/senziesdashboard:0.3
    container_name: rahasakdashboard
    ports:
        - 4000:4000
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - MONGO_DB=${MONGO_DB}
    links:
        - mongodb


mysql:
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
        ['$MYSQL_DATA_DIR:/var/lib/mysql']


studentportal:
    image: hpcal1/ucscstudentportal:1.0
    container_name: studentportal
    ports:
        - 3000:3000
    environment:
        - MYSQL_HOST=${MYSQL_HOST}
        - MYSQL_USERNAME=${MYSQL_USERNAME}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DB=${MYSQL_DB}
        - EXPRESS_SERVER_PORT=${EXPRESS_SERVER_PORT}
        - SECRET_KEY=${SECRET_KEY}
        - ENCRYPT_KEY=${ENCRYPT_KEY}
        - OPENING_DATE=${OPENING_DATE}
        - CLOSING_DATE=${CLOSING_DATE}
        - PGW_HOST=${PGW_HOST} 
        - PGW_PORT=${PGW_PORT} 
    links:
        - mysql


paymentportal:
    image: erangaeb/paymentportal:0.7 
    container_name: paymentportal
    ports:
        - 4000:80
    environment:
        - NODE_HOST=${NODE_HOST} 
        - NODE_PORT=${NODE_PORT} 
        - PGW_HOST=${PGW_HOST} 
        - PGW_PORT=${PGW_PORT} 
        - PGW_END_POINT=${PGW_END_POINT} 
        - PGW_AUTH_TOKEN=${PGW_AUTH_TOKEN} 
        - PGW_HMAC_SECRET=${PGW_HMAC_SECRET} 
        - PGW_MODE=${PGW_MODE} 


nginx:
    image: erangaeb/senznginx:0.9
    container_name: nginx
    ports:
        - 80:80
        - 443:443
    links:
        - rahasakweb
        - studentportal
        - paymentportal
